# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your needs

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '*.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
    publishTestResults: true

- task: PublishCodeCoverageResults@2
  displayName: Collect Code Coverage
  inputs: 
    summaryFileLocation: $(Agent.TempDirectory)/*/coverage.cobertura.xml

- task: CmdLine@2
  inputs:
    script: 'tree'

- script: 'nohup dotnet ECommerceTest.API.dll'
  workingDirectory: '$(System.DefaultWorkingDirectory)/ECommerceTest.API/bin/Release/net8.0'
  env:
    ASPNETCORE_URLS: 'http://localhost:8888/'
    ConnectionStrings__DefaultConnection: 'Server=tcp:ecommercetest-sql.database.windows.net,1433;Initial Catalog=ecommercetest-sql;Persist Security Info=False;User ID=${dbUser};Password=${dbPassword};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'

- script: 'nohup dotnet ECommerceTest.Frontend.dll'
  workingDirectory: '$(System.DefaultWorkingDirectory)/ECommerceTest.Frontend/bin/Release/net8.0'
  env:
    ASPNETCORE_URLS: 'http://localhost:8889/'

- task: Npm@1
  displayName: Install newman
  inputs:
    command: 'custom'
    customCommand: 'install newman -g'

- task: Bash@3
  displayName: Run newman
  inputs:
    targetType: 'inline'
    script: 'newman run ./Postman/ECommerceTest.postman_collection.json -r cli,junit --env-var api_url=http://localhost:8888'

- task: PublishTestResults@2
  displayName: Publish Postman Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/newman-run-report*.xml'
    
- task: UsePythonVersion@0
  inputs:
    versionSpec: '>=3.8.3'
    addToPath: true
    architecture: 'x64'

- script: 'export DISPLAY=:1'
  displayName: Set Display Environment Variable

- script: 'python -m pip install -r requirements.txt'
  workingDirectory: 'RobotFramework'
  displayName: Install Robot Framework requirements

- script: 'python -m robot -d "results" -x "xunit" --nostatusrc --variable BROWSER:headlesschrome tests/products.robot'
  displayName: Run Robot Framework tests
  workingDirectory: 'RobotFramework'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'xunit.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/RobotFramework/results'
    failTaskOnFailedTests: true

- task: PublishPipelineArtifact@1
  displayName: Publish Robot Framework Reports
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/RobotFramework/results'
    artifact: 'Robot Framework Reports'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'ECommerceTest.API/**.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'ECommerceTest'

- task: PublishPipelineArtifact@1
  displayName: Publish Robot Framework Test files Artifact
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/RobotFramework' 
    artifactName: 'Robot Framework Test Files'

- task: PublishPipelineArtifact@1
  displayName: Publish Postman Test files Artifact
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/Postman' 
    artifactName: 'Postman Test Files'