version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./ECommerceTest.API/Dockerfile
    image: ghcr.io/johanhcarlberg/ecommercetest_api
    ports:
      - "8888:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ECommerceDB;User Id=sa;Password=strongPassword1;TrustServerCertificate=true
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./ECommerceTest.Frontend/Dockerfile
    image: ghcr.io/johanhcarlberg/ecommercetest_frontend
    ports:
      - "8889:8080"
    environment:
      - API__Api.Host=api
      - API__Api.Port=8080
  db:
    build:
      context: .
      dockerfile: ./mssql-docker/Dockerfile
    image: ghcr.io/johanhcarlberg/ecommercetest_db
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=strongPassword1
      - DATABASE=ECommerceDB
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U sa", "-P strongPassword1", "-Q", "SELECT 1"]
      interval: 1s
      retries: 30
